version: "3"

services:
  django:
    build: ./backend
    command: ["pipenv", "run", "start"]
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    command: ["yarn", "start"]
    volumes:
      - ./frontend:/app/frontend
      - node_modules:/app/frontend/node_modules
    ports:
      - "3000:3000"
    tty: true

volumes:
  node_modules:
