version: "3"

services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"

  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/app/frontend
      - node_modules:/app/frontend/node_modules
    ports:
      - "3000:3000"
    tty: true

volumes:
  node_modules:
