FROM python:3.7

ENV BACKEND_DIR /app/backend
WORKDIR ${BACKEND_DIR}

RUN pip install --upgrade pip setuptools wheel

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .
EXPOSE 8000
CMD ["uwsgi", "uwsgi.ini"]